#!/bin/bash

read -p 'MySQL Username: ' usr &&
read -sp 'MySQL Password: ' pw &&
read -p 'Your Bin-Address:port/ Ex. localhost:3306/: ' ba &&
read -p 'Your Database Target: ' db &&
spark-submit --jars mysql-connector-java-5.1.49-bin.jar script.py $usr $pw $ba $db &&

mysql -u $usr -p$pw <<MY_QUERY
use $db
ALTER TABLE AWBuildVersion MODIFY ModifiedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
CREATE TABLE Address2 SELECT AddressID, AddressLine1, AddressLine2, City, StateProvinceID, PostalCode,  ST_GeomFromText(SpatialLocation) AS SpatialLocation, rowguid, ModifiedDate FROM Address;
ALTER TABLE BillOfMaterials MODIFY EndDate DATETIME NULL, MODIFY ModifiedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE CurrencyRate MODIFY ModifiedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE EmployeePayHistory MODIFY ModifiedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE Product MODIFY SellEndDate DATETIME NULL, MODIFY DiscontinuedDate DATETIME NULL, MODIFY ModifiedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE ProductCostHistory MODIFY EndDate DATETIME NULL, MODIFY ModifiedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE ProductListPriceHistory MODIFY EndDate DATETIME NULL, MODIFY ModifiedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE ProductReview MODIFY ModifiedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE ProductVendor MODIFY ModifiedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE PurchaseOrderDetail MODIFY ModifiedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE PurchaseOrderHeader MODIFY ShipDate DATETIME NULL, MODIFY ModifiedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE SalesOrderHeader MODIFY DueDate DATETIME, MODIFY ShipDate DATETIME NULL, MODIFY ModifiedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE SalesPersonQuotaHistory MODIFY ModifiedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE SalesTerritoryHistory MODIFY EndDate DATETIME NULL, MODIFY ModifiedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE Shift MODIFY StartTime TIME, MODIFY EndTime TIME, MODIFY ModifiedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE ShoppingCartItem MODIFY ModifiedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE SpecialOffer MODIFY EndDate DATETIME, MODIFY ModifiedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE TransactionHistory MODIFY ModifiedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE TransactionHistoryArchive MODIFY ModifiedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE WorkOrder MODIFY EndDate DATETIME NULL, MODIFY DueDate DATETIME, MODIFY ModifiedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE WorkOrderRouting MODIFY ScheduledEndDate DATETIME, MODIFY ActualStartDate DATETIME NULL, MODIFY ActualEndDate DATETIME NULL, MODIFY ModifiedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
MY_QUERY
